### ISSUE TITLE
CenntOS + PHP 5.6.21 安装时编译错误

### ISSUE THREAD

**Issue by One2r** [imaben/php-akm#5]
在CenntOS PHP 5.6.21环境下，make是错误，具体如下:

_/bin/sh /root/Downloads/php-akm/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/Downloads/php-akm -DPHP_ATOM_INC -I/root/Downloads/php-akm/include -I/root/Downloads/php-akm/main -I/root/Downloads/php-akm -I/usr/local/php-5.6.21/include/php -I/usr/local/php-5.6.21/include/php/main -I/usr/local/php-5.6.21/include/php/TSRM -I/usr/local/php-5.6.21/include/php/Zend -I/usr/local/php-5.6.21/include/php/ext -I/usr/local/php-5.6.21/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/Downloads/php-akm/akm.c -o akm.lo 
mkdir .libs
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/Downloads/php-akm -DPHP_ATOM_INC -I/root/Downloads/php-akm/include -I/root/Downloads/php-akm/main -I/root/Downloads/php-akm -I/usr/local/php-5.6.21/include/php -I/usr/local/php-5.6.21/include/php/main -I/usr/local/php-5.6.21/include/php/TSRM -I/usr/local/php-5.6.21/include/php/Zend -I/usr/local/php-5.6.21/include/php/ext -I/usr/local/php-5.6.21/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/Downloads/php-akm/akm.c  -fPIC -DPIC -o .libs/akm.o
/root/Downloads/php-akm/akm.c:29:28: error: zend_smart_str.h: No such file or directory
/root/Downloads/php-akm/akm.c:97:19: error: macro "zend_hash_add" requires 6 arguments, but only 3 given
/root/Downloads/php-akm/akm.c: In function ‘akm_build_tree’:
/root/Downloads/php-akm/akm.c:95: error: ‘zend_hash_add’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:95: error: (Each undeclared identifier is reported only once
/root/Downloads/php-akm/akm.c:95: error: for each function it appears in.)
/root/Downloads/php-akm/akm.c: In function ‘akm_dict_ht_free’:
/root/Downloads/php-akm/akm.c:193: error: ‘zend_string’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:193: error: ‘key’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:198: error: expected ‘;’ before ‘{’ token
/root/Downloads/php-akm/akm.c: At top level:
/root/Downloads/php-akm/akm.c:210: error: expected ‘)’ before ‘_’ token
/root/Downloads/php-akm/akm.c: In function ‘php_akm_enable’:
/root/Downloads/php-akm/akm.c:226: error: request for member ‘len’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:230: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c: In function ‘php_akm_dict_dir’:
/root/Downloads/php-akm/akm.c:241: error: request for member ‘len’ in something not a structure or union
/root/Downloads/php-akm/akm.c:244: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:244: error: request for member ‘len’ in something not a structure or union
/root/Downloads/php-akm/akm.c:245: error: request for member ‘len’ in something not a structure or union
/root/Downloads/php-akm/akm.c:245: error: request for member ‘len’ in something not a structure or union
/root/Downloads/php-akm/akm.c:246: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:247: error: request for member ‘len’ in something not a structure or union
/root/Downloads/php-akm/akm.c:248: error: request for member ‘len’ in something not a structure or union
/root/Downloads/php-akm/akm.c:250: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:250: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:250: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:250: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:250: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:250: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c:250: error: request for member ‘val’ in something not a structure or union
/root/Downloads/php-akm/akm.c: At top level:
/root/Downloads/php-akm/akm.c:272: error: expected ‘)’ before ‘_’ token
/root/Downloads/php-akm/akm.c:272: error: expected ‘;’, ‘,’ or ‘)’ before ‘void’
/root/Downloads/php-akm/akm.c:293: error: expected ‘)’ before ‘_’ token
/root/Downloads/php-akm/akm.c:319: error: expected ‘)’ before ‘_’ token
/root/Downloads/php-akm/akm.c: In function ‘zif_akm_match’:
/root/Downloads/php-akm/akm.c:353: error: ‘zend_string’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:353: error: ‘dict’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:354: error: ‘text’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:374: error: ‘akm_match_handler’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c: In function ‘zif_akm_replace’:
/root/Downloads/php-akm/akm.c:382: error: ‘zend_string’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:382: error: ‘dict’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:386: error: ‘ht’ redeclared as different kind of symbol
/root/Downloads/php-akm/akm.c:377: note: previous definition of ‘ht’ was here
/root/Downloads/php-akm/akm.c:400: warning: passing argument 1 of ‘zend_parse_parameters’ makes integer from pointer without a cast
/usr/local/php-5.6.21/include/php/Zend/zend_API.h:257: note: expected ‘int’ but argument is of type ‘struct HashTable _’
/root/Downloads/php-akm/akm.c:410: warning: assignment makes pointer from integer without a cast
/root/Downloads/php-akm/akm.c:427: error: ‘akm_replace_handler’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:431: error: ‘smart_str’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:431: error: expected ‘;’ before ‘replaced’
/root/Downloads/php-akm/akm.c:440: error: expected ‘;’ before ‘{’ token
/root/Downloads/php-akm/akm.c:469: error: ‘replaced’ undeclared (first use in this function)
/root/Downloads/php-akm/akm.c:474: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/php-5.6.21/include/php/Zend/zend_variables.h:51: note: expected ‘struct zval *_’ but argument is of type ‘struct zval _’
make: *_\* [akm.lo] Error 1_

**Comment by imaben** [comment]
php5请编译php5版本 https://github.com/imaben/php-akm/tree/php5

**Comment by One2r** [comment]
已安装成功，建议在readme中进行说明下。
