### ISSUE TITLE
关于akm_replace函数参数设计

### ISSUE THREAD

**Issue by One2r** [imaben/php-akm#6]
akm_replace函数参数设计为：

```
Function [ <internal:akm> function akm_replace ] {
  - Parameters [3] {
    Parameter #0 [ <required> $dict_name ]
    Parameter #1 [ <required> &$text ]
    Parameter #2 [ <required> $callback ]
  }
}
```

我的疑问是：
设计时，为什么不考虑设计四个参数，第三个参数为敏感词的替换词如$replace，第四个参数为$callback。第三、四参数为可选参数。
我是想，假如需求是将敏感词统一替换的话，不必要用都回调处理，直接用第三个参数替换词处理。

另一想法是，对不同敏感词做不同替换，通过拓展词典方式增加敏感词的替换文本（如：关键词|扩展文本|替换词）来做有什么利弊。

**Comment by imaben** [comment]
这样做是给用户更多的选择权，因为有时候一个词典中既有敏感词，也有一些其它例如需要SEO加链接的詞，这些词的类型可以通过extension扩展文本来识别，然后如果是敏感词的话就用*来替换，需要加链接的词就加上链接。你说的也有道理，其实还是三个参数就可以了，第三个参数可以传string，也可以传callback,传string的时候会直接替换，传callback就按照现在的逻辑执行！谢谢您的建议！

**Comment by One2r** [comment]
是的，第三个参数这样设计可以满足。

**Comment by imaben** [comment]
另外extension不只是可以放文本，json也可以，更灵活
