### ISSUE TITLE
一看测试用例就知道大兄弟不是做php开发的

### ISSUE THREAD

**Issue by reatang** [imaben/php-akm#8]

**Comment by imaben** [comment]
怎么说？

**Comment by reatang** [comment]
<?php
$dict_name = 'dict';
$text = file_get_contents("text.txt");

$start = microtime(true);
$result = akm_match($dict_name, $text);
$end = microtime(true);
echo '耗时' . ($end - $start) . "毫秒\n";
echo '内存占用:' . memory_get_usage() / 1024 / 1024 . "MB\n";

**Comment by imaben** [comment]
哈哈，才疏学浅！回头改正！😄

**Comment by reatang** [comment]
代码真是漂亮
