### ISSUE TITLE
akm.c:403: error: ‘key’ undeclared (first use in this function) make: *** [akm.lo] Error 1

### ISSUE THREAD

**Issue by wangyulu** [imaben/php-akm#9]
make 
/usr/local/src/phpakm/php-akm-dict-automatic-update-dev/akm.c:403: error: ‘key’ undeclared (first use in this function)
make: *** [akm.lo] Error 1
Is this what causes it

**Comment by imaben** [comment]
你下载的是开发分支，还没开发完，请用release包

**Comment by imaben** [comment]
php5的话用php5的分支即可

**Comment by wangyulu** [comment]
谢谢，已解决！
